name: Update visitor map

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  refresh-map:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Update visitor map data
        env:
          VISITOR_MAP_ENDPOINT: ${{ secrets.VISITOR_MAP_ENDPOINT }}
          VISITOR_MAP_API_TOKEN: ${{ secrets.VISITOR_MAP_API_TOKEN }}
        run: |
          python scripts/update_visitor_map.py

      - name: Commit and push if changed
        run: |
          if git diff --quiet -- _data/visitor_map.yml; then
            echo "No visitor map updates to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _data/visitor_map.yml
          git commit -m "chore: update visitor map data"
          git push
